/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.turing.javase7.pos.UI;

import com.turing.javase7.pos.Service.App;
import com.turing.javase7.pos.Service.AuthService;
import com.turing.javase7.pos.Service.CategoryService;
import com.turing.javase7.pos.Service.ItemService;
import com.turing.javase7.pos.Service.OrderService;
import com.turing.javase7.pos.model.Category;
import com.turing.javase7.pos.model.Item;
import com.turing.javase7.pos.model.Order;
import com.turing.javase7.pos.model.User;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class OrderUI extends javax.swing.JFrame {
    App app = App.getSingleton();
    OrderService orderService = app.getOrderService();
    ItemService itemService = app.getItemService();
    CategoryService categoryService = app.getCategoryService();
    AuthService authService = app.getAuthService();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderUI.class.getName());

    /**
     * Creates new form OrderUI
     */
    public OrderUI() {
        initComponents();
        this.loadAddItem();
        
    }
    
    public void loadAddItem(){
        ArrayList<Item> items = this.itemService.getAllItems();
        DefaultTableModel model = (DefaultTableModel)this.tblItem.getModel();
        model.setRowCount(0);
        for(Item item : items){
            Object[] row = new Object[5];
            row[0] = item.id();
            row[1] = item.name();
            row[2] = item.price();
            row[3] = item.stockAmount();
            row[4] = this.getCategoryForItem(item.id());
            model.addRow(row);
        }
    }
    
    public String getCategoryForItem(int itemId){
        ArrayList<Category> categories = this.categoryService.getAllCategoryByItemId(itemId);
        String str = "";
        for(Category category : categories){
            if(str.length()>0){
                str += ", "+category.name();
            }else{
                str+=category.name();
            }
        }
        return str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();

        setTitle("Order Page");

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Price", "Stock_Amount", "Category"
            }
        ));
        jScrollPane1.setViewportView(tblItem);

        jLabel1.setText("Quantity");

        jButton1.setText("Add Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "UserId", "ItemId", "Date", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblOrder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.addOrder();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void addOrder(){
        int row = this.tblItem.getSelectedRow();
        if(row != -1){
            User user = this.authService.getAuthUser();
            int userId = user.id();
            int itemId = (int)this.tblItem.getModel().getValueAt(row, 0);
            Date date = new Date();
            int quantity = Integer.parseInt(this.txtQuantity.getText().toString());
            int total = this.getTotal();
            this.orderService.addOrder(userId, itemId, date, quantity, total);
            this.getOrderForUser(userId);
            this.txtQuantity.setText("");
        }
        
        
        

        
    }
    
    public int getTotal(){
        int row = this.tblItem.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "Please select an item!");
            return 0;
        }
        int price = (int)this.tblItem.getModel().getValueAt(row, 2);
        int stockAmount = (int)this.tblItem.getModel().getValueAt(row, 3);

        int quantity;

        try{
            quantity = Integer.parseInt(this.txtQuantity.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid quantity!");
            return 0;
        }

        if(quantity <= 0){
            JOptionPane.showMessageDialog(null, "Quantity must be greater than 0!");
            return 0;
        }

        if(quantity > stockAmount){
            JOptionPane.showMessageDialog(null, "Stock amount is insufficient!");
            return 0;
        }

        int total = price * quantity;
        return total;
    }
    
    
    public void getOrderForUser(int userId ){
        ArrayList<Order> orders = this.orderService.getAllOrdersByUser(userId);
        DefaultTableModel model = (DefaultTableModel)this.tblOrder.getModel();
        model.setRowCount(0);
        for(Order order : orders){
            Object[] row = new Object[6];
            row[0] = order.id();
            row[1] = order.userId();
            row[2] = order.itemId();
            row[3] = order.date();
            row[4] = order.quantity();
            row[5] = order.total();
            model.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
